version: '3.9'

services:
  postgres:
    container_name: next_postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: next_app
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:
