services:
  app:
    container_name: next_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "yarn prisma migrate deploy && yarn db:seed && yarn dev"

volumes:
  postgres_data:
