services:
  postgres:
    container_name: next_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course_platform
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d course_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: next_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app:cached
      - prisma_node_modules:/app/node_modules

volumes:
  postgres_data:
  prisma_node_modules:
