services:
  postgres:
    container_name: next_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d course_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: next_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "yarn prisma migrate deploy && yarn db:seed && yarn dev"

volumes:
  postgres_data:
