import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { PageWrapper } from '@/shared/ui/layout/PageWrapper';

export const metadata: Metadata = {
  title: 'Next Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="course-platform-light">
      <body>
        <Providers>
          <PageWrapper>{children}</PageWrapper>
        </Providers>
      </body>
    </html>
  );
}
