name: PR Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete Neon branch for PR
        uses: neondatabase/delete-branch-action@v1
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: pr-${{ github.event.pull_request.number }}
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
